# Generated by Django 2.1.3 on 2019-05-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(blank=True, default='', max_length=100, verbose_name='Nama Jurusan')),
                ('fakultas', models.CharField(choices=[('FTT', 'Fakultas Teknik dan Teknologi Informasi'), ('FKES', 'Fakultas Kesehatan')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=100, unique=True)),
                ('nama', models.CharField(blank=True, default='', max_length=100, verbose_name='Nama Mahasiswa')),
                ('aktif', models.BooleanField(default=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jurusan_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Jurusan')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Matakuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matakuliah', models.CharField(blank=True, default='', max_length=100, verbose_name='Matakuliah')),
                ('sks', models.IntegerField(verbose_name='SKS')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('mahasiswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Mahasiswa')),
                ('matakuliah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Matakuliah')),
            ],
        ),
    ]
