# Generated by Django 2.1.3 on 2019-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nama',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nama Mahasiswa'),
        ),
    ]
