# Generated by Django 2.1.3 on 2019-04-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nim', models.TextField(unique=True)),
                ('nama', models.CharField(blank=True, default='', max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('jurusan', models.CharField(choices=[('tif', 'Teknik Informatika'), ('si', 'Sistem Informasi'), ('tin', 'Teknik Industri')], default='python', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
