# Generated by Django 2.1.3 on 2019-04-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190407_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
