# Generated by Django 2.1.3 on 2019-04-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190410_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='fakultas',
            field=models.CharField(choices=[('FTT', 'Fakultas Teknik dan Teknologi Informasi'), ('FKES', 'Fakultas Kesehatan')], default='FTT', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(choices=[('tif', 'Teknik Informatika'), ('si', 'Sistem Informasi'), ('tin', 'Teknik Industri'), ('d3-si', 'D3 Sistem Informasi')], max_length=100),
        ),
    ]
