# Generated by Django 2.1.3 on 2019-04-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20190410_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='jurusan',
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Jurusan'),
        ),
    ]
